=== pigamux/pigamux.github.io/games/edc/aEvolucaoDaConfianca.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT aEvolucaoDaConfianca (original, traducao, personagens, narrativa)>
<!ELEMENT original (autor, data, livro)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT livro (titulo, autor, ano)>
<!ELEMENT titulo (#PCDATA|negrito)*>
<!ELEMENT ano (#PCDATA)>
<!ELEMENT traducao (tradutor, data, instituicao, unidadeCurricular)>
<!ELEMENT tradutor (#PCDATA)>
<!ELEMENT instituicao (#PCDATA)>
<!ELEMENT unidadeCurricular (#PCDATA)>
<!ELEMENT personagens (personagem+)>
<!ELEMENT personagem (#PCDATA|nome|estrategiaDeJogo)*>
<!ATTLIST personagem
    id CDATA #REQUIRED>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT estrategiaDeJogo (#PCDATA)>
<!ELEMENT narrativa (titulo, subtitulo, introducao, umJogo, jogoRepetido, umTorneio, torneiosRepetidos, aEvolucaoDaDesconfianca, cometimentoDeErrod, conclusao)>
<!ELEMENT subtitulo (#PCDATA)>
<!ELEMENT introducao (paragrafo+)>
<!ELEMENT umJogo (paragrafo+)>
<!ELEMENT jogoRepetido (paragrafo+)>
<!ELEMENT umTorneio (paragrafo+)>
<!ELEMENT torneiosRepetidos (paragrafo+)>
<!ELEMENT aEvolucaoDaDesconfianca (paragrafo+)>
<!ELEMENT cometimentoDeErrod (paragrafo|item)*>
<!ELEMENT conclusao (paragrafo+)>
<!ELEMENT paragrafo (#PCDATA|titulo|negrito|italico|rasurado|item|citacao|personagem)*>
<!ELEMENT negrito (#PCDATA|personagem)*>
<!ELEMENT italico (#PCDATA|personagem)*>
<!ELEMENT rasurado (#PCDATA)>
<!ELEMENT item (#PCDATA|negrito|italico|personagem)*>
<!ELEMENT citacao (#PCDATA|italico)*>

=== pigamux/pigamux.github.io/games/edc/aEvolucaoDaConfianca.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE aEvolucaoDaConfianca SYSTEM "aEvolucaoDaConfianca.dtd">

<aEvolucaoDaConfianca>
    <original>
        <autor>Nicky Case</autor>
        <data>julho de 2017</data>
        <livro>
            <titulo>"A Evolução da Coopereação"</titulo>
            <autor>Robert Axelrod</autor>
            <ano>1984</ano>
        </livro>
    </original>
    <traducao>
        <tradutor>Luís Costa</tradutor>
        <data>maio de 2021</data>
        <instituicao>Universidade do Minho</instituicao>
        <unidadeCurricular>Informática Aplicada (LAD)</unidadeCurricular>
    </traducao>
    <personagens>
        <personagem id="1">
            <nome>Copião</nome>
            <estrategiaDeJogo>Começa com Cooperar. Em seguida, simplesmente repete o que quer que TU tenhas feito na última ronda.</estrategiaDeJogo>
        </personagem>
        <personagem id="2">
            <nome>Traidor</nome>
            <estrategiaDeJogo>Trai sempre.</estrategiaDeJogo>
        </personagem>
        <personagem id="3">
            <nome>Cooperador</nome>
            <estrategiaDeJogo>Coopera sempre.</estrategiaDeJogo>
        </personagem>
        <personagem id="4">
            <nome>Rancoroso</nome>
            <estrategiaDeJogo>Começa com Cooperar, e continua a cooperar até tu traíres a confiança dele uma vez que seja. Se tal tiver acontecido, joga sempre Trair.</estrategiaDeJogo>
        </personagem>
        <personagem id="5">
            <nome>Detetive</nome>
            <estrategiaDeJogo>Começa com: Cooperar, Trair, Cooperar, Cooperar. Depois, se tu retaliares alguma vez com uma Traição, ele joga como o Copião. Caso contrário, joga como o Traidor.</estrategiaDeJogo>
        </personagem>
        <personagem id="6">
            <nome>Copiinho</nome>
            <estrategiaDeJogo>Começa com Cooperar. Só retalia com uma Traição se tu tiveres traído a confiança dele DUAS VEZES seguidas.</estrategiaDeJogo>
        </personagem>
        <personagem id="7">
            <nome>Simplório</nome>
            <estrategiaDeJogo>Começa com Cooperar. Depois, se tu cooperaste na última ronda, ele repete a sua última jogada (mesmo que tenha sido um acidente). Mas se tu o traíste na última ronda, ele altera a sua última jogada (mesmo que tenha sido um acidente).</estrategiaDeJogo>
        </personagem>
        <personagem id="8">
            <nome>Aleatório</nome>
            <estrategiaDeJogo>Trai ou coopera aleatoriamente com 50/50 de chance.</estrategiaDeJogo>
        </personagem>
    </personagens>
    <narrativa>
        <titulo>A Evolução da Confiança</titulo>
        <subtitulo>um guia interativo para a teoria dos jogos do porquê e como confiamos uns nos outros</subtitulo>
        <introducao>
            <paragrafo>Durante a Primeira Guerra Mundial, a paz eclodiu.</paragrafo>
            <paragrafo>Era o Natal de 1914 na Frente Ocidental.
            Apesar de ordens claras para <italico>não</italico> ficar à vontade com o inimigo, soldados ingleses e alemães deixaram as suas trincheiras, atravessaram a Terra de Ninguém, e reuniram-se para enterrar os seus mortos, trocar presentes e jogar uns jogos.</paragrafo>
            <paragrafo>Entretanto: é 2017, o Ocidente está em paz há décadas, e
            uau, somos uns <italico>zeros à esquerda</italico> no que toca a confiança. Pesquisas mostram que, nos últimos quarenta anos, cada vez menos pessoas dizem que confiam umas nas outras. Eis então o nosso enigma:</paragrafo>
            <paragrafo><negrito>Porque é que, mesmo em tempos de paz, amigos se tornam inimigos? E porque é que, mesmo em tempos de guerra, inimigos se tornam amigos?</negrito></paragrafo>
            <paragrafo>Penso que a <negrito>teoria dos jogos</negrito> consegue ajudar a explicar a nossa epidemia de desconfiança – e como a podemos consertar! Vamos jogar um jogo.</paragrafo>
        </introducao>
        <umJogo>
            <paragrafo><titulo><negrito>O Jogo da Confiança</negrito></titulo>Tens uma escolha a fazer. À tua frente está uma máquina: se inserires uma moeda na máquina, o <italico>outro jogador</italico> recebe três moedas – e vice-versa. Vocês os dois podem escolher ou COOPERAR (inserir moeda), ou TRAIR (não inserir moeda).</paragrafo>
            <paragrafo><negrito>Suponhamos que o outro jogador trai a tua confiança, e não insere nenhuma moeda.</negrito> O que é que tu deverias fazer?</paragrafo>
            <paragrafo>Se tu cooperares e ele te trair, tu perdes uma moeda e ele ganha três. (pontuação: -1 vs +3) No entanto, se vocês os dois traírem a confiança do outro, nenhum de vocês ganha nada nem perde nada. (pontuação: 0 vs 0) <negrito>Ou seja: deves TRAIR.</negrito></paragrafo>
            <paragrafo><negrito>Mas suponhamos que o outro jogador coopera, e insere uma moeda.</negrito> O que é que tu deverias fazer desta vez?</paragrafo>
            <paragrafo>Porque se vocês os dois cooperarem, ambos abdicam de uma moeda para ganhar três. (pontuação: +2 vs +2) Mas se tu o traíres e ele cooperar contigo, tu ganhas três moedas pelo preço de uma. (pontuação: +3 vs -1) <negrito>Ou seja: ainda "deves" TRAIR.</negrito></paragrafo>
            <paragrafo>E é <italico>esse</italico> o nosso dilema. Confiar é bom, mas pode fazer com que os outros se aproveitem de ti -- ou que disparem contra ti enquanto sais desarmado de uma trincheira. Às vezes, a desconfiança é racional! Vamos jogar este jogo mais do que uma vez.</paragrafo>
        </umJogo>
        <jogoRepetido>
            <paragrafo><negrito>Agora, vamos jogar a sério.</negrito> Vais jogar contra 5 adversários diferentes, cada um com a sua própria "estratégia" de jogo. Contra cada adversário, vais jogar um certo número de rondas, que pode variar entre 3 e 7. (Não vais saber com antecedência quando é a última ronda) Será que podes confiar neles? Ou melhor... será que eles podem confiar em <italico>ti?</italico></paragrafo>
            <paragrafo>As personagens:
                <item><negrito><personagem id="1">Copião</personagem>:</negrito> Olá! Eu começo com Cooperar, e posteriormente, apenas copio o que quer que tu tenhas jogado na última ronda. Miau</item>
                <item><negrito><personagem id="2">Traidor</personagem>:</negrito> <italico>o forte comerá o fraco</italico></item>
                <item><negrito><personagem id="3">Cooperador</personagem>:</negrito> 'Bora ser melhores amigos! &lt;3</item>
                <item><negrito><personagem id="4">Rancoroso</personagem>:</negrito> Olha aqui, parceiro. Eu começo a cooperar, e continuo a cooperar, mas se tu me traíres uma vez que seja, eu vou-te trair até ao último dos teus dias.</item>
                <item><negrito><personagem id="5">Detetive</personagem>:</negrito> Primeiro, eu analiso-o. Começo a Cooperar consigo, Traio-o, Coopero, Coopero. Se me trair de volta, passarei a agir como o <personagem id="1">Copião</personagem>. Se nunca me trair de volta, passarei a agir como o <personagem id="2">Traidor</personagem>, para explorá-lo. Elementar, meu caro Watson.</item></paragrafo>
        </jogoRepetido>
        <umTorneio>
            <paragrafo>É hora do torneio! Cada personagem vai agora jogar contra cada uma das outras personagens: o que perfaz 10 partidas de pares, e 10 rondas por partida.</paragrafo>
            <paragrafo>Quem é que achas que terá a maior pontuação <italico>total?</italico></paragrafo>
            <paragrafo>Oh, já agora... É possível que estejas cético quanto àquela história da Trégua de Natal sobre as trincheiras da Primeira Guerra Mundial. De certeza que foi só um acaso... certo?</paragrafo>
            <paragrafo>Sim, a trégua foi dramática, mas não foi <italico>nem única, nem invulgar</italico>.</paragrafo>
            <paragrafo>Nem <italico>todas</italico> as trincheiras aderiram à paz, mas até que ela foi bem difundida. Várias linhas de frente tiveram essa mesma ideia independentemente, e repito: <italico>apesar</italico> das ordens específicas e bem claras para não o fazer.</paragrafo>
            <paragrafo>E de facto, mesmo <italico>antes</italico> do Natal, várias linhas de frente já <italico>tinham</italico> estabelecido uma paz secreta não-oficial.</paragrafo>
            <paragrafo>Chamaram-lhe: <negrito>o sistema "vive e deixa viver"</negrito>. Basicamente, tu não disparas contra mim, eu não disparo contra ti. E este sistema funcionou, em muitos lugares!</paragrafo>
            <paragrafo>Pode ser que aindas estejas cético. A maioria dos soldados não forma paz espontaneamente com o inimigo. O que é que há de tão especial na guerra de <italico>trincheiras</italico>?</paragrafo>
            <paragrafo>Bem, eis o que é único sobre as trincheiras: ao contrário de quase todas as outras formas de guerra, os soldados enfrentam os <italico>mesmos soldados</italico> todos os dias.</paragrafo>
            <paragrafo><negrito>É um jogo repetido.</negrito> E isso faz <italico>toda</italico> a diferença.</paragrafo>
            <paragrafo>Enfim. E o vencedor é... o <negrito><personagem id="1">Copião</personagem>!</negrito></paragrafo>
            <paragrafo>O <personagem id="1">Copião</personagem> tem muitos nomes. A Regra de Ouro, altruísmo recíproco, olho por olho, ou... <negrito>vive e deixa viver.</negrito> É por isso que a "paz" pôde emergir nas trincheiras da Primeira Guerra Mundial: quando se é obrigado a jogar o mesmo jogo com as <italico>mesmas pessoas</italico> (não só o mesmo "inimigo" genérico) uma e outra vez -- O <personagem id="1">Copião</personagem> não ganha só a batalha, ele vence a guerra.</paragrafo>
            <paragrafo>Mas se as coisas mudam bastante quando se joga várias rondas do mesmo jogo, vamos ver o que acontece se jogarmos <italico>vários torneios.</italico></paragrafo>
        </umTorneio>
        <torneiosRepetidos>
            <paragrafo>Agora, deixemos a nossa população de jogadores <italico>evoluir com o passar do tempo</italico>. É uma dança de 3 passos:
