=== pigamux/pigamux.github.io/games/p/pirilampos.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT pirilampos (original, traducao, narrativa)>
<!ELEMENT original (autor, ano, livro)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT ano (#PCDATA)>
<!ELEMENT livro (titulo, autor, link)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT traducao (tradutora, data, instituicao, unidadeCurricular)>
<!ELEMENT tradutora (#PCDATA)>
<!ELEMENT instituicao (#PCDATA)>
<!ELEMENT unidadeCurricular (#PCDATA)>
<!ELEMENT narrativa (titulo|p)*>
<!ELEMENT p (#PCDATA|italico)*>
<!ELEMENT italico (#PCDATA)>

=== pigamux/pigamux.github.io/games/p/pirilampos.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE pirilampos SYSTEM "pirilampos.dtd">

<pirilampos>
	<original>
		<autor>Nicky Case</autor>
		<ano>2017</ano>
		<livro>
			<titulo>SYNC: How Order Emerges From Chaos In the Universe, Nature, and Daily Life</titulo>
			<autor>Steven Strogatz</autor>
			<link>http://www.powells.com/book/sync-how-order-emerges-from-chaos-in-the-universe-nature-daily-life-9780786887217</link>
	</original>
	<traducao>
		<tradutora>Lia dos Reis</tradutora>
		<data>maio de 2021</data>
        <instituicao>Universidade do Minho</instituicao>
        <unidadeCurricular>Informática Aplicada (LAD)</unidadeCurricular>
	</traducao>
	<narrativa>
		<titulo>Pirilampos</titulo>
		<p>Como luzes de Natal a flutuar suavemente no ar, pirilampos acrescentam sempre um pouco de magia às florestas em que vivem.</p>
		<p>Mas algumas espécies de pirilampos acrescentam ainda <italico>mais</italico> magia. No sudeste da Ásia, se fores até à margem do rio no meio da noite, serás presenteado com este impressionante show de luzes - cortesia do pirilampo da Tailândia:</p>
		<p>Um manguezal inteiro a iluminar-se de uma vez só, mergulhando na escuridão, e então iluminando tudo outra vez - numa sincronia quase perfeita. Como é que milhares de pirilampos se coordenam uns com os outros? Quem é o maestro desta sinfonia silenciosa?</p>
		<p>Isto foi um mistério por quase um século e, em 1992,uma equipa de cientistas americanos decidiu resolvê-lo. Infelizmente, mas não surpreendentemente, a imprensa gozou com eles — <italico>“O Governo queima os nossos impostos €€ para estudar pirilampos em Bornéu: Não é uma ideia brilhante!”</italico> disse uma revista. Implacáveis, os cientistas seguiram em frente, câmaras e calculadoras nas mãos.</p>
		<p>Então, <italico>como é que</italico> milhares de pirilampos escolhem um líder para seguir, um maestro para manter os seus sinais luminosos em sincronia? A resposta, os cientistas descobriram, é simples:</p>
		<p>Eles não escolhem.</p>
		<p>Cada pirilampo tem o seu <italico>próprio</italico> relógio interno individual e, sempre que o relógio “bate as doze horas”, ele pisca.</p>
		<p>E em vez de sincronizar os seus relógios com um líder central, cada pirilampo faz o seguinte:</p>
		<p>Etapa 1: quando vê um sinal luminoso próximo de outro pirilampo, adianta um pouco o seu relógio.</p>
		<p>Etapa 2: e é isso.</p>
		<p>Será que uma interação tão pequena e de curto alcance pode realmente fazer uma floresta inteira de pirilampos piscar numa harmonia sincrónica? Só há uma maneira de descobrir...</p>
		<p>Espera. Vê com atenção.</p>
		<p>O que é que vês?</p>
		<p>No início, não muito. Os pirilampos ainda parecem estar a piscar sem um padrão.</p>
		<p>Mas, depois de um tempo, vais notar pequenos grupos de pirilampos a piscarem juntos — mas esses grupos individuais ainda estão dessincronizados.</p>
		<p>Depois de um pouco mais de tempo, vais começar a ver pirilampos a fazer uma "onda",como fãs empolgados nas bancadas durante um jogo de beisebol.</p>
		<p>Finalmente, todos, exceto alguns pirilampos, piscam juntos — e, eventualmente, até mesmo os atrasados juntam-se à dança coletiva.</p>
		<p>Há algo mais incrível do que isso? Se interromperes estes pirilampos causando algum caos...</p>
		<p>... sim, isso pode fazer com que eles se dividam por um momento, mas lenta e certamente, eles recompor-se-ão e brilharão como um.</p>
		<p>Aqui estão mais alguns botões e barras deslizantes que podes usar, para brincar com estes pirilampos virtuais:</p>
		<p>E este é o segredo por trás do truque de magia dos nossos pirilampos:</p>
		<p> Acontece que os pirilampos não são as únicas coisas que se sincronizam de baixo para cima. Os teus neurónios criam ondas cerebrais. As células do pacemaker do teu coração disparam em sincronia.
		<p>Até mesmo um monte de metrónomos sem vida numa plataforma instável começarão a marchar juntos.</p>
		<p>Além de tudo isso, entender a auto-sincronia ajudou-nos a construir melhores lasers, computadores e tecnologia de comunicação!</p>
		<p>E pensar que a matemática dos sistemas de auto-sincronização foi descoberta em parte por alguns cientistas que realmente amavam pirilampos. Parece que chamar o projeto deles de <italico>“Não é uma Ideia Brilhante”</italico> não foi uma ideia brilhante.</p>
		<p>Tu flutuas em conjunto, suavemente, em silêncio, ocasionalmente pontuando a escuridão com um pequeno ponto de luz brilhante. Sozinho, não há muito para ver.</p>
		<p>Mas, sempre que brilhas, inspiras aqueles perto de ti a brilharem também, um pouco mais cedo do que eles brilhariam. E aqueles perto de ti, por sua vez, inspiram aqueles perto <italico>deles</italico>.</p>
		<p>E assim por diante.</p>
		<p>Primeiro, alguns pequenos grupos começam a piscar juntos. Depois, uma onda de luz varre o enxame. Finalmente, estão todos deslumbrantes juntos, um farol brilhante, todos em harmonia, em tandem — em sincronia.</p>
		<p>Que interação em pequena escala farás hoje, pequeno pirilampo?</p>
	</narrativa>
</pirilampos>
